#!/usr/bin/env python3
from sea_ice_rs.install import install

install()

import sys
import os
import shutil
import argparse
import numpy as np
from sea_ice_rs.utils import decompose_filepath
from sea_ice_rs.ML_tools import (
    config_parser,
    claculate_hidden_layer_size,
    process_data,
    learning_curve,
    tr_val_split,
    CNN,
)
from keras.callbacks import ModelCheckpoint


def main(args):
    # Parse configuration
    num_epochs, hidden_size, verbosity, K = config_parser(args.dl_config)

    # Set up results directory
    config_dir, filename, _ = decompose_filepath(args.dl_config)
    result_dir = os.path.join(
        ".".join(config_dir.split("/")[:-1]), f"results/CNN_{filename}"
    )
    try:
        os.mkdir(result_dir)
    except FileExistsError:
        shutil.rmtree(result_dir)
        os.mkdir(result_dir)

    # Verbosity == 1 --> sys.stdout
    # Verbosity == 2 --> .log file
    if verbosity == 2:
        log_file = open(f"{result_dir}/train.log", "w")
        sys.stdout = log_file

    # Modify train dataset
    X_tr, Y_tr, _ = process_data(args.train_data, args.dl_config)

    # Define hidden layer size
    input_layer_size = X_tr.shape[1]
    output_layer_size = len(np.unique(Y_tr))
    hidden_layer_size = claculate_hidden_layer_size(
        input_layer_size, output_layer_size, hidden_size
    )

    # K-fold classification
    tr_val_pairs = tr_val_split(K, X_tr, Y_tr)

    for iter, (train, validation) in enumerate(tr_val_pairs):
        checkpoint_path = f"{result_dir}/cp.ckpt"
        cp_callback = ModelCheckpoint(
            filepath=checkpoint_path, save_weights_only=True, verbose=1
        )

        model = CNN(hidden_layer_size, input_layer_size, output_layer_size)

        # Format X for CNN
        formatted_X_tr = np.transpose(np.array([np.transpose(X_tr[train])]))
        formatted_X_val = np.transpose(np.array([np.transpose(X_tr[validation])]))

        # Train the model
        model_summary = model.fit(
            x=formatted_X_tr,
            y=Y_tr[train],
            epochs=num_epochs,
            batch_size=5,
            verbose=verbosity,
            validation_data=(formatted_X_val, Y_tr[validation]),
            callbacks=[cp_callback],
        )

        # Plot the learning curve
        learning_curve(model_summary.history, result_dir, iter)

    # stdout redirection closed
    if verbosity == 2:
        log_file.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--train-data", type=str, help="CSV file containing train data")
    parser.add_argument(
        "--dl-config",
        type=str,
        help="YAML file containing the configuration for deep learning",
    )

    args = parser.parse_args()
    main(args)
