#!/usr/bin/env python3
import argparse
from sea_ice_rs.utils import decompose_filepath
from sea_ice_rs.data_processing import GLCM_handler

def main(args):
    parent_dir, filename, extension = decompose_filepath(args.input)
    GLCM_handler(parent_dir, args.input, args.img_extension, args.img_dir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--input", type=str, help="Input csv/image file")
    parser.add_argument("--img-dir", type=str, help="Directory with raw data")
    parser.add_argument(
        "--img-extension", type=str, help="extension of the raw images", default="jpg"
    )

    args = parser.parse_args()
    main(args)
