#!/usr/bin/env python3
from sea_ice_rs.install import install

install()

import argparse
import numpy as np
import cv2
import os
from tqdm import tqdm
from skimage.feature import greycoprops
from sea_ice_rs.utils import mkdir_output
from sea_ice_rs.data_processing import generate_GLCM
from sea_ice_rs.data_processing import contrast


def main(args):
    if os.path.isdir(args.input):  # A collection of input images
        dirname = args.input
        pbar = tqdm(os.listdir(dirname))
        for img_f in pbar:
            pbar.set_description(img_f)
            GLCM_matrices = generate_GLCM(f"{dirname}/{img_f}")

            entropy_img = glcm_product(GLCM_matrices, "entropy", dirname, img_f)
            ASM_img = glcm_product(GLCM_matrices, "ASM", dirname, img_f)
            contrast_img = glcm_product(GLCM_matrices, "contrast", dirname, img_f)
            homogeneity_img = glcm_product(GLCM_matrices, "homogeneity", dirname, img_f)
            dissimilarity_img = glcm_product(
                GLCM_matrices, "dissimilarity", dirname, img_f
            )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--input", type=str, help="Input file/directoy path")

    args = parser.parse_args()
    main(args)
