#!/usr/bin/env python3
from sea_ice_rs.install import install

install()

import argparse
import os
import cv2
import csv
from tqdm import tqdm
from sea_ice_rs.utils import decompose_filepath


def main(args):
    with open(f"{args.input}_pix_features.csv", "w", newline="") as file:
        writer = csv.writer(file)

        for img_f in tqdm(os.listdir(args.input)):
            _, filename, extension = decompose_filepath(img_f)
            if extension != "jpg":
                continue
            patch_num = filename.split("-")[0][1:]
            year = filename.split("-")[1][0:4]
            month = filename.split("-")[1][4:6]
            day = filename.split("-")[1][6:8]
            hour = filename.split("-")[1][8:10]

            inImage = cv2.imread(f"{args.input}/{img_f}")
            for row in range(inImage.shape[0]):
                for col in range(inImage.shape[1]):
                    pix_vals = inImage[row][col]
                    writer.writerow(
                        [
                            patch_num,
                            year,
                            month,
                            day,
                            hour,
                            row,
                            col,
                            pix_vals[0],
                            pix_vals[1],
                            pix_vals[2],
                        ]
                    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--input", type=str, help="Input directoy path")

    args = parser.parse_args()
    main(args)
