#!/usr/bin/env python3
from sea_ice_rs.install import install

install()

import argparse
import os
import sys
import cv2
import numpy as np
from skimage import filters
from sea_ice_rs.utils import (
    process_single_input,
    process_multiple_inputs,
)
from sea_ice_rs.contrast import contrast


def main(args):
    if os.path.isfile(args.input):  # Only one input image is provided
        process_single_input(
            args.input,
            "SOBEL",
            args.extension,
            filters.sobel,
            contrast_bool=args.contrast,
        )

    elif os.path.isdir(args.input):  # A collection of input images
        process_multiple_inputs(
            args.input,
            "SOBEL",
            args.extension,
            filters.sobel,
            contrast_bool=args.contrast,
        )

    else:
        sys.exit(f"Provided input does not exist")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--input", type=str, help="Input file/directoy path")
    parser.add_argument("--contrast", action="store_true", help="Enhannces contrast")
    parser.add_argument(
        "--extension",
        type=str,
        help="Output file extension(e.g. png, jpg, tiff)",
        choices=["png", "jpg", "tiff"],
    )

    args = parser.parse_args()
    main(args)
